version: '3.3'

volumes:
  mongodb_data:
  mysql_data:

services:
  mongo:
    image: bitnami/mongodb
    volumes:
      - 'mongodb_data:/Users/Shared/mongodb'
    ports:
      - "27017:27017"

  mysql:
    image: bitnami/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - 'mysql_data:/Users/Shared/mysql'
    ports:
      - "3306:3306"
